version: '2.1'
services:

  # service that includes serverless
  # used for deployments in make deploy
  locutus-deploy:
    build:
      context: .
      dockerfile: docker/locutus-deploy/Dockerfile
    env_file: ${DOCKER_ENV_FILE:-envvars}


  # service that includes test dependencies
  # used to run tests
  locutus:
    build:
      context: .
      dockerfile: docker/locutus/Dockerfile
    working_dir: /app
    environment:
      - TEST
      - CC_TEST_REPORTER_ID
      - GOOGLE_API_KEY
      - GIT_BRANCH
      - GIT_COMMIT_SHA
    env_file: ${DOCKER_ENV_FILE:-envvars}
    volumes:
      - .:/app

  # used to build py package in make dist
  locutus-dist:
    image: python:3.6
    working_dir: /app
    command: python setup.py bdist_wheel
    volumes:
      - .:/app
