service: locutus 

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6
  memorySize: 512
  timeout: 60
  stage: dev
  region: us-east-1
  versionFunctions: false
  environment:
    app: locutus
    stage: ${self:custom.stage, 'dev'}

# Package explicitly for complete control over what's included
package:
  excludeDevDependencies: false
  exclude:
    - ./**
  include:
    - .requirements.zip
    - locutus/**

functions:
  ecovacs:
    handler: locutus.handlers.ecovacs_handler
    environment:
      stage: ${env:stage}
    events:
      - alexaSmartHome: amzn1.ask.skill.5763cd14-1dc1-48e0-ac3c-4fc7bcbf4f88 
